version: '3.1'
services:
  website:
    image: trafex/alpine-nginx-php7
    container_name: "lab1_php"
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site:/var/www/html
