login: ENC[AES256_GCM,data:PUlUNVhtK34=,iv:A4/3PTc+IQUFAVuW1xEKLYYhnmEJBK3AUoi06649UIw=,tag:M5sghpFsShBIGG7y8x/yWw==,type:str]
password: ENC[AES256_GCM,data:0rojonU+fQDat1Q=,iv:BQptz8m60kFG0Mzly8ELbN7vl3rzmqKOKz7SwHL4z0c=,tag:PFIrjl8KoY1JKjGJTXOLCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-13T23:37:07Z"
    mac: ENC[AES256_GCM,data:GnNdJCf44ezHfRbA6iVkD3GJslI84tn/Uz3WRzBjz3aZE1j0OZ6xEKwWpkTLZaPSlAxFl7aEJb5A4pAK0Vun8To8hOHEFBncTZ56+X+0kvaPNqdYTdLCLgMIb511XrJvdfvj8Y/lik7IoWlu+m/wtUFDtrlyzw12M1EizeKvAiU=,iv:rOejm9vr+3eyfGvbdvL+pWfhGp8ChAe79XLV37GtR8o=,tag:aXtOIOuwnaDbnenJClQnnQ==,type:str]
    pgp:
        - created_at: "2022-11-13T23:36:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA9ebz3CRDj6pAQv/cJBDPi5eSt43+gtdj1yWwtoYyQS6dZORVIbUApjv0/tY
            /T+fop73JZNAL21saAVWAjbaBxa3yEKnzuktu/t7YgFwhazN6zKk70IcMMxKtRRs
            RNpJ5zUGRA6KY1AO3r4fejtJjBihQ+c1JFX6OArABK9YdtW0e+3vg77fiKRimVII
            KsVOZrQ0o0IiBdKZzwBW5lYZRP63v4YQN08RfdRB0XSdBT0kJPArzRMLWM71zA6t
            2D9/L1s5Iy+U2YQVyFjjUAJ6uGSIjdxhLguanIKgWM7UE60FldnFwy69CWvrQCzl
            yNh5g9WE/k2GU12wJqUblr89oA4B5DFjXPxhUGaoowsA0z60RdGF4ZDA27+RDNPD
            GGB9wdLxOe9jvUmtheZBZ9iNquzTLZWLmfYg7K8CS9dQjsmeNm5uKuuCqbAUbBkN
            EyqoCsJq6HKHNOxKdx678oDM1eAAzp/bauyGxkJMkekPn8zHyB2csmWT347Nog3j
            LSgdxfkX7ne1I5Imk5Mu0l4B2FbjlxhQk9bNajN+d1ipm/QYETgYov3w5fagbNI3
            J7jS8DbZiYk/GDzajShbsS9zYr4h5Sz41EB9niL0aiwkC7ROgXAkl5eKNkLjsxJF
            2hkHGF2N3S80YANWp+kg
            =qLcb
            -----END PGP MESSAGE-----
          fp: 08DEC5D15FCE948FDE36F63E62A666BD8E0E6065
    unencrypted_suffix: _unencrypted
    version: 3.7.3
