global:
   scrape_interval: 5s

scrape_configs:
  - job_name: app_python
    static_configs:
      - targets:
          - app_python:80

  - job_name: app_php
    static_configs:
      - targets:
          - app_php_metrics:9113

  - job_name: promtail
    static_configs:
      - targets:
          - promtail:9080

  - job_name: loki
    static_configs:
      - targets:
          - loki:3100

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
