name: app_php_docker

on: 
  push:
    paths:
      - 'app_php/**'
      - '.github/workflows/app_php.yml'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app_php
          file: ./app_php/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:php_lab3
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:php_lab3_buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:php_lab3_buildcache,mode=max
