name: app_python

on: [push]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: ./app_python
        run: |
          python -V
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Run linters
        working-directory: ./app_python
        run: |
          make lint

      - name: Run tests
        working-directory: ./app_python
        run: |
          make test
