name: app_python_docker

on: 
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/app_python.yml'
      - '.github/workflows/app_python_docker.yml'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

        # Use tmpfs in order to build arm/v7 and linux/386 images
        # https://github.com/JonasAlfredsson/docker-nginx-certbot/issues/109
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 12

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app_python
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:python_lab3
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:python_lab3_buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/iu-devops:python_lab3_buildcache,mode=max
